# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

workflows:
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:16.7.0
    steps:
      - checkout
      - run: # print the name of the branch we're on
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          name: Restore Cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          name: Save Cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Format Code
          command: npm run format:check
      - run:
          name: Lint Code
          command: npm run affected:lint
      - run:
          name: Run Tests
          command: npm run affected:test
