# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

workflows:
  test:
    jobs:
      - format_test

jobs:
  format_test:
    docker:
      - image: cimg/node:16.7.0
    steps:
      - checkout
      - run: |
          if [ "$CIRCLE_BRANCH" = "master" ]; then
              circleci-agent step halt
          fi
      - restore_cache:
          name: Restore Cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          name: Save Cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Print Circle Branch
          command: echo ${CIRCLE_BRANCH}~1
      - run:
          name: Format Code
          command: npm run format:check --base=${CIRCLE_BRANCH}~1 --head=HEAD --parallel
      - run:
          name: Lint Code
          command: npm run affected:lint --base=${CIRCLE_BRANCH}~1 --head=HEAD --parallel
      - run:
          name: Run Tests
          command: npm run affected:test --base=${CIRCLE_BRANCH}~1 --head=HEAD --code-coverage --parallel
          parallelism: 4
      - run:
          name: List affected apps command
          command: echo nx affected:apps --base=${CIRCLE_BRANCH}~1 --head=HEAD
      - run:
          name: List affected apps command 2
          command: echo nx affected:apps --base=${CIRCLE_BRANCH} --head=HEAD
      - run:
          name: List affected apps
          command: nx affected:apps --base=${CIRCLE_BRANCH}~1 --head=HEAD
