version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.2.0

jobs:
  identify_affected_applications:
    docker:
      - image: cimg/node:16.7.0
    steps:
      - checkout
      - run:
          name: Install Nx cli
          command: npm i @nrwl/cli
      - run:
          name: List affected apps
          command: npm run listAffectedApps
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  Prerequisites:
    jobs:
      - identify_affected_applications
      - continuation/continue:
          requires:
            - identify_affected_applications
          # parameters: ./affectedApplications.json
          parameters: '{"applicationName": ["properties"]}'
          configuration_path: ./.circleci/pipeline.yml
